defmodule MiniLineageWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :mini_lineage

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  # The cookie carries an opaque character id and nothing else. `max_age` matches the 24h the
  # character row itself lives, so closing the browser no longer loses a character the database
  # is still holding. `secure` is set for a deployment behind TLS.
  @session_options [
    store: :cookie,
    key: "_mini_lineage_key",
    signing_salt: "boRfKEv2",
    same_site: "Lax",
    http_only: true,
    secure: System.get_env("IN_DOCKER") == "true",
    max_age: 24 * 60 * 60
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :mini_lineage,
    gzip: not code_reloading?,
    only: MiniLineageWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :mini_lineage
  end

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug MiniLineageWeb.Router
end
