services:
  mini-lineage:
    build: .
    container_name: mini-lineage
    restart: always
    ports:
      - "${PORT:-4000}:${PORT:-4000}"
    environment:
      - PORT=${PORT:-4000}
      - PHX_HOST=${PHX_HOST:-localhost}
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
