defmodule MiniLineage.Game.ParityTest do
  @moduledoc """
  Cross-stack parity against the TypeScript reference, on the layer the balance golden master does
  not reach: the exact narrative and flash STRINGS, and every derived number in a player snapshot.

  The golden master pins nine integers at the end of 400 fights. This replays twelve shorter runs
  frame by frame — every purchase message, every narrative line, the stat pipeline, the XP curve,
  the effect tooltips — against a fixture generated by running the reference implementation itself.
  A formatting difference that never moves a golden integer still fails here.
  """
  use ExUnit.Case, async: true

  alias MiniLineage.Game.{Battle, Clock, Constants, Math, Narrative, Player, Snapshot}
  alias MiniLineage.Test.Lcg

  @fixture "test/fixtures/parity.json" |> File.read!() |> Jason.decode!()
  @frozen_now 1_700_000_000_000

  # 1 and 1.0 are the same number to JSON but not to a map comparison, and a percentage crosses
  # the two stacks as one or the other depending on the value.
  defp norm(value) when is_float(value) do
    if value == Float.round(value), do: trunc(value), else: Float.round(value, 6)
  end

  defp norm(%{} = value), do: Map.new(value, fn {k, v} -> {to_string(k), norm(v)} end)
  defp norm(value) when is_list(value), do: Enum.map(value, &norm/1)

  defp norm(value) when is_atom(value) and value not in [nil, true, false],
    do: Atom.to_string(value)

  defp norm(value), do: value

  defp snapshot_frame(player) do
    view = Snapshot.build(player)

    norm(%{
      "health" => view.health,
      "max_health" => view.max_health,
      "hp_percent" => view.hp_percent,
      "low_health" => view.low_health,
      "experience" => view.experience,
      "level" => view.level,
      "is_max_level" => view.is_max_level,
      "xp_current" => view.xp_current,
      "xp_required" => view.xp_required,
      "xp_percent" => view.xp_percent,
      "xp_needed" => view.xp_needed,
      "adena" => view.adena,
      "weapon_id" => view.weapon.id,
      "armor_id" => view.armor.id,
      "stats" => %{
        "attack" => view.stats.attack,
        "defense" => view.stats.defense,
        "crit" => view.stats.crit,
        "regen" => view.stats.regen,
        "ambush_risk" => view.stats.ambush_risk,
        "xp_multiplier" => view.stats.xp_multiplier,
        "adena_multiplier" => view.stats.adena_multiplier
      },
      "effects" =>
        Enum.map(view.effects, fn e ->
          %{
            "id" => e.id,
            "type" => e.type,
            "emoji" => e.emoji,
            "label" => e.label,
            "tooltip" => e.tooltip
          }
        end)
    })
  end

  defp outcome_frame(o) do
    norm(%{
      "enemiesKilled" => o.enemies_killed,
      "hpLost" => o.hp_lost,
      "damageBlocked" => o.damage_blocked,
      "xpGained" => o.xp_gained,
      "adenaGained" => o.adena_gained,
      "isCritical" => o.is_critical,
      "isLevelUp" => o.is_level_up
    })
  end

  defp play(race_id, start_seed, purse) do
    Lcg.install(start_seed)
    Clock.put_now(@frozen_now)

    {player, flash} = Player.initialize(%Player{}, Constants.race(race_id), "Hero#{race_id}")
    # A deliberately wealthy run buys the top tier at once, then walks back down the tiers as its
    # purse drains — the only path any test takes through the innate crit and regen modifiers.
    player = if purse, do: %{player | adena: purse}, else: player
    {player, _} = Player.sync_zone_auras(%{player | current_screen: "home"})

    frames = [%{"kind" => "start", "flash" => flash.text, "snapshot" => snapshot_frame(player)}]

    {player, frames} =
      Enum.reduce_while(1..30, {player, frames}, fn _fight, {player, frames} ->
        if player.dead, do: {:halt, {player, frames}}, else: {:cont, fight(player, frames)}
      end)

    frames ++
      [%{"kind" => "end", "dead" => player.dead, "death_reason" => player.death_reason}]
  end

  defp fight(player, frames) do
    {player, frames} = buy_best(player, frames, "weapon", Constants.weapons(), :weapon_id)
    {player, frames} = buy_best(player, frames, "armor", Constants.armors(), :armor_id)
    {player, frames} = maybe_eat(player, frames)

    {player, _} = Player.sync_zone_auras(%{player | current_screen: "battle", ambushed: false})

    outcome = Battle.simulate(player)
    {player, level_up?} = Player.resolve_battle_outcome(player, outcome)
    outcome = %{outcome | is_level_up: level_up?}

    {player, frames} =
      if player.dead do
        {player, frames}
      else
        ambushed = Math.ambush_chance?(Player.stats(player).ambush_risk)

        player =
          if ambushed,
            do: %{player | ambushed: true, total_ambushes: player.total_ambushes + 1},
            else: player

        n = Narrative.build_battle(player, outcome, ambushed)

        frame = %{
          "kind" => "fight",
          "outcome" => outcome_frame(outcome),
          "ambushed" => ambushed,
          "narrative" =>
            norm(%{
              "crit_line" => n.crit_line,
              "kill_line" => n.kill_line,
              "deflection_line" => n.deflection_line,
              "outcome_line" => n.outcome_line,
              "ambush_line" => n.ambush_line,
              "fight_prompt" => n.fight_prompt,
              "next_move" => n.next_move
            }),
          "snapshot" => snapshot_frame(player)
        }

        {player, frames ++ [frame]}
      end

    {player, _} = Player.process_effect_expiry(player)
    {player, _} = Player.process_regen_tick(player)

    {player, frames}
  end

  defp buy_best(player, frames, type, list, slot) do
    (length(list) - 1)..1//-1
    |> Enum.reduce_while({player, frames}, fn id, {player, frames} ->
      item = Enum.at(list, id)

      if Map.get(player, slot) != id and player.adena >= item.cost do
        {player, result} = Player.purchase(player, type, id)
        {:halt, {player, frames ++ [%{"kind" => "purchase", "text" => result.text}]}}
      else
        {:cont, {player, frames}}
      end
    end)
  end

  defp maybe_eat(player, frames) do
    if player.health < Player.stats(player).max_health / 2 do
      foods = Constants.foods()

      (length(foods) - 1)..0//-1
      |> Enum.reduce_while({player, frames}, fn id, {player, frames} ->
        if player.adena >= Enum.at(foods, id).cost do
          {player, result} = Player.purchase(player, "food", id)
          {:halt, {player, frames ++ [%{"kind" => "purchase", "text" => result.text}]}}
        else
          {:cont, {player, frames}}
        end
      end)
    else
      {player, frames}
    end
  end

  for {key, _frames} <- @fixture do
    test "#{key} reproduces the reference frame for frame" do
      [_, kind, race_id, seed] = Regex.run(~r/^(race|rich)(\d+)-seed(\d+)$/, unquote(key))
      purse = if kind == "rich", do: 3_000_000
      expected = Map.fetch!(@fixture, unquote(key))
      actual = play(String.to_integer(race_id), String.to_integer(seed), purse)

      assert length(actual) == length(expected)

      for {a, e} <- Enum.zip(actual, expected) do
        assert a == norm(e)
      end
    end
  end
end
