defmodule MiniLineage.Board do
  @moduledoc """
  The Halls of Champions: every run that has chosen a race, best first, alive or finished.

  It is a view of `characters` rather than a table of its own, which is what lets a run appear the
  moment it starts and keep its place when it ends. The columns it sorts on are generated by
  Postgres from the character's document, so they cannot drift from it.

  This process exists to make it live without making it expensive. Characters broadcast that they
  were written; a burst of fights would otherwise have every viewer re-query for every write, so
  the refresh is coalesced into one recomputation per window and pushed to everyone at once.
  """
  use GenServer

  import Ecto.Query

  alias MiniLineage.Characters.Record
  alias MiniLineage.Game.{Constants, Math}
  alias MiniLineage.Repo

  @topic "board"
  # Long enough to swallow a flurry of fights, short enough that a climb still feels live.
  @coalesce_ms 500

  def start_link(_opts), do: GenServer.start_link(__MODULE__, :ok, name: __MODULE__)

  @doc "Subscribe to pushed refreshes. The message is `{:board, boards}`, keyed by race filter."
  def subscribe, do: Phoenix.PubSub.subscribe(MiniLineage.PubSub, @topic)

  @doc "Tell the board a character was written. Cheap and asynchronous — never blocks the writer."
  def character_changed do
    if pid = Process.whereis(__MODULE__), do: send(pid, :changed)

    :ok
  end

  @doc """
  Every board as it stands, for a viewer who has just arrived. Computed in the caller when the
  process is not running — which is how tests read a board without a timer firing queries at them
  from outside their sandbox.
  """
  def current do
    case Process.whereis(__MODULE__) do
      nil -> compute()
      pid -> GenServer.call(pid, :current)
    end
  end

  @doc """
  Where this run stands among all of them, counting from 1 — so a player outside the top can still
  be shown their own place. Nil for a run that is not ranked at all.
  """
  def rank_of(%{race_id: nil}), do: nil
  def rank_of(%{disqualified: true}), do: nil

  def rank_of(entry) do
    # One statement, two index-only scans. The count has to be split — an OR-chain over the two
    # cases cannot use the board index and scans the whole table — but it must not be split into
    # two QUERIES: a round trip to the database costs ~0.8ms here, which is more than either scan.
    ahead =
      ranked()
      |> where(
        [r],
        fragment("(?, ?) > (?, ?)", r.total_xp, r.adena, ^entry.total_xp, ^entry.adena)
      )
      |> select([r], %{count: count()})

    # Exactly level on both, and got there first. Rare, but it is what keeps the rank on a player's
    # own row agreeing with where the list above it would have put them.
    tied =
      ranked()
      |> where(
        [r],
        r.total_xp == ^entry.total_xp and r.adena == ^entry.adena and
          r.inserted_at < ^entry.inserted_at
      )
      |> select([r], %{count: count()})

    behind = Repo.one(from s in subquery(union_all(ahead, ^tied)), select: sum(s.count))

    Decimal.to_integer(behind) + 1
  end

  @doc "One run by its public id, for its own page. Disqualified runs still render their own."
  def entry(id) do
    Record
    |> where([r], r.id == ^id and not is_nil(r.race_id))
    |> select([r], map(r, ^fields()))
    |> Repo.one()
    |> decorate()
  end

  @impl true
  def init(:ok) do
    {:ok, %{boards: compute(), timer: nil}}
  end

  @impl true
  def handle_call(:current, _from, state), do: {:reply, state.boards, state}

  @impl true
  def handle_info(:changed, %{timer: nil} = state),
    do: {:noreply, %{state | timer: Process.send_after(self(), :refresh, @coalesce_ms)}}

  # Already waiting to refresh: the write it is waiting for has simply been joined by another.
  def handle_info(:changed, state), do: {:noreply, state}

  def handle_info(:refresh, state) do
    boards = compute()
    Phoenix.PubSub.broadcast(MiniLineage.PubSub, @topic, {:board, boards})

    {:noreply, %{state | boards: boards, timer: nil}}
  end

  # One list per filter the screen offers, so a viewer on "Elves" is served by the same push as a
  # viewer on "All" rather than querying for themselves.
  defp compute do
    Map.new([nil | Enum.map(Constants.races(), & &1.id)], &{&1, top(&1)})
  end

  defp top(race_id) do
    ranked()
    |> then(&if race_id, do: where(&1, [r], r.race_id == ^race_id), else: &1)
    |> order_by([r], desc: r.total_xp, desc: r.adena, asc: r.inserted_at, desc: r.id)
    |> limit(^Constants.highscores_limit())
    |> select([r], map(r, ^fields()))
    |> Repo.all()
    |> Enum.map(&decorate/1)
  end

  # A run is ranked once it has chosen a race. A coward's and a cheat's never is — their own page
  # still renders, which is why this is a board rule rather than a deletion.
  defp ranked, do: from(r in Record, where: not is_nil(r.race_id) and r.disqualified == false)

  # Selected into a plain map, never a %Record{}: the schema struct carries `session_id`, and an
  # entry that has the key at all is one `Repo.all(Record)` away from carrying the secret with it.
  defp fields, do: ~w(id name race_id total_xp adena dead disqualified inserted_at)a

  defp decorate(nil), do: nil

  # Level is derived from experience by the same function the character screen uses, so the two can
  # never disagree — and it is why there is no generated column for it.
  defp decorate(entry), do: Map.put(entry, :level, Math.level_for_xp(entry.total_xp))
end
