defmodule MiniLineage.Characters.Record do
  @moduledoc """
  The stored row. `id` is public — it is what a board link carries — and `session_id` is the
  secret the cookie holds, so knowing a champion's link never lets you play as them. A finished
  run keeps its id and loses its session.

  The remaining fields are generated by Postgres from `state` and are read-only here: the board
  sorts on them, and deriving them in the database is what stops them drifting from the document.
  """
  use Ecto.Schema

  @primary_key {:id, :string, autogenerate: false}
  schema "characters" do
    field :session_id, :string
    field :state, :map

    field :name, :string, read_after_writes: true
    field :race_id, :integer, read_after_writes: true
    field :total_xp, :integer, read_after_writes: true
    field :adena, :integer, read_after_writes: true
    field :dead, :boolean, read_after_writes: true
    field :disqualified, :boolean, read_after_writes: true

    timestamps(type: :utc_datetime_usec)
  end
end
