defmodule MiniLineage.Characters.Record do
  @moduledoc """
  The stored row. `id` is public and goes in board links; `session_id` is the cookie's secret, so
  a champion's link is never a way to play as them. The rest are generated by Postgres from
  `state` and read-only here, which is what stops them drifting from the document.
  """
  use Ecto.Schema

  @primary_key {:id, :string, autogenerate: false}
  schema "characters" do
    field :session_id, :string
    field :state, :map

    # Never written by Ecto, and never read back after a save, which throws the row away.
    field :name, :string, writable: :never
    field :race_id, :integer, writable: :never
    field :total_xp, :integer, writable: :never
    field :adena, :integer, writable: :never
    field :dead, :boolean, writable: :never
    field :disqualified, :boolean, writable: :never

    timestamps(type: :utc_datetime_usec)
  end
end
