defmodule MiniLineage.Characters.Record do
  @moduledoc """
  The stored row. `id` is public and goes in board links; `session_id` is the cookie's secret, so
  a champion's link is never a way to play as them. The rest are generated by Postgres from
  `state` and read-only here, which is what stops them drifting from the document.
  """
  use Ecto.Schema

  @primary_key {:id, :string, autogenerate: false}
  schema "characters" do
    field :session_id, :string
    field :state, :map

    field :name, :string, read_after_writes: true
    field :race_id, :integer, read_after_writes: true
    field :total_xp, :integer, read_after_writes: true
    field :adena, :integer, read_after_writes: true
    field :dead, :boolean, read_after_writes: true
    field :disqualified, :boolean, read_after_writes: true
    field :last_action_at, :utc_datetime_usec, read_after_writes: true

    timestamps(type: :utc_datetime_usec)
  end
end
