import Config

# Stamped at BUILD time. A release has no git checkout, so runtime.exs could not work this out at
# boot — and without it the footer says "development" AND `Version.release?/1` stays false, which
# is what keeps error detail from reaching players. APP_VERSION wins, so a Docker build (whose
# context carries no .git) can pass the sha in.
app_version =
  case System.get_env("APP_VERSION") do
    given when is_binary(given) and given != "" ->
      given

    _ ->
      try do
        case System.cmd("git", ["rev-parse", "--short=7", "HEAD"], stderr_to_stdout: true) do
          {sha, 0} -> String.trim(sha)
          _ -> nil
        end
      rescue
        _ -> nil
      end
  end

config :mini_lineage, :app_version, app_version

# Whatever the version turned out to be, a production build tells a player nothing.
config :mini_lineage, debug_build: false

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :mini_lineage, MiniLineageWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json"

# Force using SSL in production. This also sets the "strict-security-transport" header,
# known as HSTS. If you have a health check endpoint, you may want to exclude it below.
# Note `:force_ssl` is required to be set at compile-time.
config :mini_lineage, MiniLineageWeb.Endpoint,
  force_ssl: [
    rewrite_on: [:x_forwarded_proto],
    exclude: [
      # paths: ["/health"],
      hosts: ["localhost", "127.0.0.1"]
    ]
  ]

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.

# Throttling is on only for a real deployment; local development is never throttled.
config :mini_lineage, rate_limit: true
